apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: younyoung
type: Opaque
data:
  FLASK_SECRET_KEY: "MTJhYmNkZWYxMjM0NTY3ODkwYWJjZGVmMTIzNDU2Nzg="  # 생성된 실제 base64 값
  MYSQL_PASSWORD: "OWx4OEdQemRQSw=="  # 9lx8GPzdPK를 base64로 인코딩
  REDIS_PASSWORD: "R2pBMFBIeDk2Tg=="  # GjA0PHx96N를 base64로 인코딩
  KAFKA_PASSWORD: ""
