name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image to ACR
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/younyoung-aks-demo-backend:${{ github.sha }} \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/younyoung-aks-demo-backend:latest .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/younyoung-aks-demo-backend:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/younyoung-aks-demo-backend:latest

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image to ACR
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/younyoung-aks-demo-frontend:${{ github.sha }} \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/younyoung-aks-demo-frontend:latest .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/younyoung-aks-demo-frontend:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/younyoung-aks-demo-frontend:latest
